### ISSUE TITLE
GPU Acceleration not working.

### ISSUE THREAD

**Issue by BrandonSmith6** [Aveygo/AstroSleuth#1]
I followed the instructions for how to enable GPU acceleration but it doesn't seem to be working. It is still maxing out my CPU and not utilizing my GPU. 

GPU Acceleration
All the above methods rely on onnxruntime for infernece, which only supports the cpu by default. For gpu support (cuda 11 and below), you can run:

pip3 uninstall onnxruntime
and then

pip3 install onnxruntime-gpu

**Comment by Aveygo** [comment]
Can you confirm that you are running CUDA 11 or below with nvidia-smi?
Unfortunately onnxruntime-gpu does not fully support the current version 12.

I added pytorch gpu support that you should now use if this is the case.
Make sure to download the latest version and follow the [new](https://github.com/Aveygo/AstroSleuth#gpu-acceleration-pytorch) instructions.
