### ISSUE TITLE
Old Model VS New Model

### ISSUE THREAD

**Issue by BrandonSmith6** [Aveygo/AstroSleuth#2]
I am a bit conflicted when it comes to the new model. It adds more details but it seems to add faint stars on the edge of where it probably does tiling. Ontop of that the amount of artifacts has gone up dramatically. Here is a small example of it. This has a ton of potential and if these artifacts are ironed out and the tiling is done in a better way this could be close to perfect!
<img width="495" alt="Screenshot 2023-06-03321312511 120540" src="https://github.com/Aveygo/AstroSleuth/assets/68724169/72fc4fbd-d040-4351-8f35-c2e92309bb78">

**Comment by Aveygo** [comment]
Sorry I took my time, but trained a new model to try and address this. Still a little ongoing as there are strange star "waves"/diffractions, but I believe this is now just a matter of proper conditioning.  

![824d27dde9de163dae897227a02226354c4b699dcab930f619fda809](https://github.com/Aveygo/AstroSleuth/assets/48315552/1d4d519f-0a97-427f-accd-7a05214b302d)
