### ISSUE TITLE
Switching models

### ISSUE THREAD

**Issue by materialvision** [Aveygo/AstroSleuth#3]
Hi, I am testing in colab, but are there some easy way to switch between model v1 and v2?  I was able to switch to model v1 by downloading it separately, and uploading it to colab and changing the names etc to match the one of v2. Running the v1 binary by changing just the VERSION parameter just hangs. It would be great if there was an easy way to do this as v1 worked great on one difficult image! 

Thanks again for your great work!

**Comment by Aveygo** [comment]
https://github.com/Aveygo/AstroSleuth/commit/43c486c70e546f129a5fed388d1a70c48f6d303c
Repo and colab updated, just make sure to re-run the cell if you select a new model.
Cheers and thanks for the feedback.
